config/routes.rb
PumaApp::Application.routes.draw do
  resources :authors do
    collection do
      post 'sort'
    end
  end

  resources :emails
  resources :notes
  resources :target_journals
  resources :variables
  resources :focus_groups
  resources :country_teams
  resources :populations
  resources :publication_types
  resources :surveys
  resources :languages
  resources :pages

  resources :publications do
    collection do
      get 'list'
      post 'import'
    end
    member do 
      put 'preplanned_submit'
      put 'preplanned_accept'
      put 'preplanned_reject' 
      put 'preplanned_remind'
      put 'planned_submit'
      put 'planned_accept'
      put 'planned_reject' 
      put 'planned_remind'
      put 'inprogress_submit'  
      put 'inprogress_accept'
      put 'inprogress_reject' 
      put 'inprogress_remind'
      put 'submitted_submit'  
      put 'submitted_accept'
      put 'submitted_reject'
      put 'submitted_remind'
      put 'accepted_submit'  
      put 'accepted_accept'
      put 'accepted_reject'
      put 'accepted_remind'
      put 'preplanned_removal_request'
      put 'planned_removal_request'
      put 'inprogress_removal_request'
      put 'submitted_removal_request'
      put 'accepted_removal_request'
      put 'published_removal_request'
      put 'removal_accept'
      put 'preplanned_removal_reject'
      put 'planned_removal_reject'
      put 'inprogress_removal_reject'
      put 'submitted_removal_reject'
      put 'accepted_removal_reject'
      put 'published_removal_reject'
      put 'unlock'
      put 'archive'
      put 'unarchive'
      get 'audit'
    end
  end

  devise_for :users
  scope "/admin" do 
    resources :users
  end

  root to: 'pages#home'
  match '/about',     to: 'pages#about'
  match '/contact',   to: 'pages#contact'
  match '/master',    to: 'pages#master' 
  match '/no_access', to: 'pages#no_access' 

end

app/models/publication_type.rb
# == Schema Information
#
# Table name: publication_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PublicationType < ActiveRecord::Base
  attr_accessible :name
  has_many :publications
  validates_presence_of :name    
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  filter_access_to :all
  # GET /publications
  # GET /publications.json

  # auto_complete_for :variable, :name
  # auto_complete_for :target_journal, :name
  def index
    # @publications = Publication.all
    @publications = Publication.find(:all, :conditions => ['archived = ?', false])
    @per_page = params[:per_page] || 5

    if(params[:search]).blank?
      @publications = Publication.paginate(:page => params[:page], :per_page => @per_page, :order => 'title', :conditions => ['archived = ?', false])
      @export = Publication.find(:all, :order => 'title', :conditions => ['archived = ?', false])
    else
      # changes for thinking sphinx
      @publications = Publication.search params[:search], 
            :page => params[:page], 
            :per_page => @per_page, 
            :match_mode => :boolean,
            :field_weights => {
              :title => 20,
              :keyword_name => 10,
              :variable_name => 5
              }
      @export = Publication.search params[:search],
              :match_mode => :boolean,
              :field_weights => {
                :title => 20,
                :keyword_name => 10,
                :variable_name => 5
              }
    end              

    # No match for your search criteria    
    if @publications.empty?
      flash[:error] = "No publications matched your search criteria."
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publications }
      format.csv { send_data Publication.to_csv(@export) }
      format.xls { send_data Publication.to_csv(@export, 
        {col_sep: "\t", encoding: "UTF-8" } ) } 
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication = Publication.find(params[:id])

    # Get previous version if requested
    if params[:version]
      @version = @publication.versions.find(params[:version])
      @publication = @version.reify

      # get hmt from meta data in versions table if available
      if !@version.keywords.nil?
        @keywords = Variable.find(YAML.load(@version.keywords))
      else
        @keywords = []
      end

      if !@version.mediators.nil?
        @mediators = Keyword.find(YAML.load(@version.mediators))
      else
        @mediators = []
      end

      if !@version.outcomes.nil?
        @outcomes = Keyword.find(YAML.load(@version.outcomes))
      else 
        @outcomes = []
      end

      if !@version.determinants.nil?
        @determinants = Keyword.find(YAML.load(@version.determinants))
      else 
        @determinants = []
      end 

      if !@version.inclusions.nil?
        @inclusions = Inclusion.find(YAML.load(@version.inclusions))
      else 
        @inclusions = []
      end 

      if !@version.foundations.nil?
        @foundations = Foundation.find(YAML.load(@version.foundations))
      else 
        @foundations = []
      end 

    else # setting them here to get least work in view
      @keywords = @publication.keywords.map{|k| Variable.find(k.variable_id)}
      @mediators = @publication.mediators.map{|k| Variable.find(k.variable_id)}
      @outcomes = @publication.outcomes.map{|k| Variable.find(k.variable_id)}
      @determinants = @publication.determinants.map{|k| Variable.find(k.variable_id)}
      @inclusions = @publication.inclusions
      @foundations = @publication.foundations
    end

    # respond to format, mostly for pdf rendering
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publication }
      # wicked_pdf
      format.pdf do
        render  :pdf => @publication.title,
               template: "publications/publication.pdf.erb",
#                :stylesheets => ["application","print"],
                # :layout => "pdf.html",
                page_size: 'A4',
                disposition: 'inline',
                orientation: 'Landscape'
                # :wkhtmltopdf  => Rails.root.join('vendor', 'wkhtmltopdf-amd64').to_s
      end      
    end
  end

  # GET /publications/new
  # GET /publications/new.json
  def new
    @publication = Publication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
    @publication.change = ""
    if (@publication.state == "preplanned_submitted" || 
        @publication.state == "planned_submitted" || 
        @publication.state == "inprogress_submitted" || 
        @publication.state == "submitted_submitted" || 
        @publication.state == "accepted_submitted") && 
        !current_user.roles.include?("publication_group")
      redirect_to @publication, notice: "Publication has been submitted and cannot be edited."
    end
    if @publication.archived 
      redirect_to @publication, notice: "Publication is archived and cannot be edited."
    end    
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        if params[:save_and_submit]
          @publication.preplanned_submit!
          format.html { redirect_to @publication, 
             notice: 'Publication was successfully created and submitted to the publication group.' }
        else
          format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
          format.json { render json: @publication, status: :created, location: @publication }
        end 
      else
        format.html { render action: "new" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.json
  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        format.html { redirect_to @publication, notice: 'Publication was successfully updated. Please note that it has been submitted to the publication group.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url }
      format.json { head :no_content }
    end
  end

  def list
    @publications = Publication.order(:id) #.paginate(:per_page => 15, :page => params[:page])
  end

  def archive
    @publication = Publication.find(params[:id])
    @publication.update_attribute :archived, true
    redirect_to list_publications_path, notice: "Publication archived."
  end
  
  def unarchive
    @publication = Publication.find(params[:id])
    @publication.update_attribute :archived, false
    redirect_to list_publications_path, notice: "Publication removed from archive to active status."
  end

  # Import
  def import
    # begin
      Publication.import(params[:file])
      flash[:notice] = "Publications imported."
    # rescue
    #   flash[:error] = "Error in data. Check your import file."
    # end
    redirect_to list_publications_url
  end

  # Workflow via aasm functions below  
  # locking to avoid concurrency issues, see
  # http://www.engineyard.com/blog/2010/concurrency-and-the-aasm-gem/

  # 2014-04-14: Meeting with PG => remove automatic email functionality for now
  # 2014-04-14: Meeting with PG => added removal request functionality to delete publication

  # preplanned to planned
  def preplanned_submit
    @publication = Publication.find(params[:id])
    @publication.lock!
    @publication.preplanned_submit!
    flash[:notice] = "Preplanned submitted for acceptance."
    # flash[:notice] = "Preplanned submitted for acceptance. Email sent to the author."
    # @email = Email.find_by_trigger('preplanned_submit')
    # Notifier.workflow_notification(@publication.user,@email,@publication).deliver
    redirect_to publication_url
  end
  
  def preplanned_accept
    @publication = Publication.find(params[:id])
    @publication.lock!
    @publication.preplanned_accept!
    flash[:notice] = "Publication accepted as planned."
    # flash[:notice] = "Publication accepted as planned. Email sent to the author."
    # @email = Email.find_by_trigger('preplanned_accept')    
    # Notifier.workflow_notification(@publication.user,@email,@publication).deliver
    redirect_to publication_url
  end
  
  def preplanned_reject
    @publication = Publication.find(params[:id])
    @publication.lock!
    @publication.preplanned_reject!
    flash[:error] = "Preplanned publication rejected."
    # flash[:error] = "Preplanned publication rejected. Email sent to the author."
    # @email = Email.find_by_trigger('preplanned_reject')    
    # Notifier.workflow_notification(@publication.user,@email,@publication).deliver
    redirect_to publication_url
  end
  
  def preplanned_remind
    @publication = Publication.find(params[:id])
    @publication.lock!
    @publication.preplanned_remind!
    # @email = Email.find_by_trigger('preplanned_remind')    
    # Notifier.workflow_notification(@publication.user,@email,@publication).deliver
    # flash[:notice] = "Pre planned publication hbsc responsible author reminder sent."
    redirect_to list_publications_path       
  end

  # planned to inprogress
  def planned_submit
    @publication = Publication.find(params[:id])
    @publication.lock!
    @publication.planned_submit!
    flash[:notice] = "Planned submitted for acceptance."
    # flash[:notice] = "Planned submitted for acceptance. Email sent to the author."
    # @email = Email.find_by_trigger('planned_submit')    

app/views/publications/_author.html.erb
<li id="author_<%= f.object[:id] %>" class="child">
  <span class="handle">[drag]</span>
  <%= f.text_field :name, :size => 20 %>
  <%= f.text_field :email, :size => 20 %>
  <%= f.collection_select :country_team_id, CountryTeam.all, :id, :name, options = { :prompt => "Select country team" } %>
  <%= f.collection_select :focus_group_id, FocusGroup.all, :id, :name, options = { :prompt => "Select focus group" } %>
  <%= remove_child_link 'Remove author', f %>
</li>

app/views/publications/_keyword.html.erb
<div class="child" id="keyword">
  <%= f.text_field_with_auto_complete :variable_name,
    {},
    { :method => :get, 
      :skip_style => true,
      :url => '/auto_complete_for_variable_name',
      :param_name => 'variable[name]'
    }
  %>
  <%= remove_child_link 'remove', f %>
</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h1>Listing publications</h1>

<%= form_tag publications_path, :method => :get do %>

<table class="table table-striped table-bordered">
  <tr>
    <td>Enter search term:<%= text_field_tag :search, params[:search], :size => 50, :autofocus => true %>
    <%= submit_tag "Search", :name => nil, :class => "btn btn-primary" %>  <p class="explanation">
    AND operator is &, OR operator is |, NOT operator is - or !, and grouping is done with parenthesis. There always is implicit AND operator, so "hello world" query actually means "hello & world".
  </p>
</td>
    <td align=right>Publications per page: <%= select_tag :per_page, options_for_select([5,10,20,50,100], params[:per_page].to_i), { size: 1 }  %></td>
  </tr>
</table> 

<table width=100%>
  <tr>
    <td>Found <%=h @publications.total_entries %> publications matching your search criteria.</td>
    <td align="right">
      <% if permitted_to? :new, :publications %>  
        <%= link_to 'New Publication', new_publication_path if permitted_to? :new, :publications %> |
      <% end %>
      <%= link_to "Download search result as spreadsheet", publications_path(:search => params[:search], :format => "xls") if permitted_to? :index, :publications %>
    </td>
  </tr>
</table>
  
<% end %>
<div id="publications">
  <%= will_paginate(@publications) %>
  <hr />
  <% for publication in @publications %>
    
      <%= link_to h(publication.title), publication if permitted_to? :show, :publications %> ( ID: <%=h publication.id %> ) 
    
  <br />
  <% if publication.publication_type.name? && publication.language.name? %>
    <i>- <%=h publication.publication_type.name %> in <%=h publication.language.name %></i>
  <% end %>
     ( <%=h publication.state %> )
  <p><%=h truncate(publication.abstract, :omission => "...", :length => 300) %>

  <%= link_to "Edit", edit_publication_path(publication) if permitted_to? :edit, :publications %> 
    <% if permitted_to? :destroy, :publications %>
  | <%= link_to "Destroy", publication, :confirm => 'Are you sure?', :method => :delete if permitted_to? :destroy, :publications %>
    <% end %>
</p>
  <hr />
  <% end %>
  <%= will_paginate(@publications) %>
</div>
<p>
      <%= link_to "Download search result as spreadsheet", publications_path(:search => params[:search], :format => "xls") if permitted_to? :index, :publications %>
</p>
<br />

<%= link_to 'New Publication', new_publication_path if permitted_to? :new, :publications %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form' %>

<p><%= link_to "Back to List", publications_path if permitted_to? :index, :publications %></p>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<table width="100%">
  <tr>
    <td width="15%" style="vertical-align:top;">
      <% if @publication.state != "published" %>
        <strong>Working Title:</strong>
      <% else %>
        <strong>Title</strong>
      <% end %>
    </td>
    <td><%=h @publication.title %></td>
    
  </tr><tr>
    <td>
      <strong>ID:</strong><td><%=h @publication.id %></td>
    </td>
  </tr><tr>
    <td>
      <strong>Created at:</strong><td><%=h @publication.created_at.strftime('%Y-%m-%d') %></td>
    </td>
  </tr><tr>
    <td>
      <strong>Updated at:</strong><td><%=h @publication.updated_at.strftime('%Y-%m-%d') %></td>
    </td>
  </tr>
<% if @publication.archived %>
  <tr>  
    <td colspan="2">
      <font style="letter-spacing:2px;font-weight:bold;color:red;">Archived</font>
    </td>
  </tr>  
<% end %>
</table>


  <% if @publication.versions.length > 1 %>
    Number of previous versions: <%=h @publication.versions.length-1 %>  
    <%= link_to_function("Show/Hide","$('#version_box').toggle();") %>
  <div id="version_box" class="well">
  <% else %>
  <div id="version_box" style="display:none;" class="well">
  <% end %>
<% @publication.versions.each do |version| %>
  <% if version == @version %>
    Version <%=h version.index.to_s %> created at <%=h localize(version.created_at, format: :short) %> by <%=h User.find(version.whodunnit.to_i).name %> is the version currently displayed<br />
  <% elsif version.event != "create" %>
    <%=h link_to "Version " + version.index.to_s, :version => version %> created at <%=h localize(version.created_at, format: :short) %> by <%=h User.find(version.whodunnit.to_i).name %><br />
  <% end %>
<% end %>
<% if params[:version] %>
  <%=h link_to "Latest version", :version => nil %>
<% end %>
</div> 
    
</p>

<div class="line_of_boxes">
  <% if @keywords %>
  <div class="box_in_line">
    Keyword(s):
    <div class="box_in_line_content">
      <% @keywords.each do |keyword| %>
        <div class="child">
            <%=h keyword.name %><br />
        </div>
      <% end %>
    </div>
  </div>
  <% end %>
   <div class="box_bottom"></div>
</div>
<table width="80%">
  <tr>
    <td><strong>Publication type:</strong>&nbsp;
      <%=h @publication.publication_type.name %></td>
    <td><strong>Language:</strong>&nbsp;
      <%=h @publication.language.name %></td>
  </tr>
</table>

<strong>Abstract:</strong> <%= @publication.abstract %>

<h3>Author(s)</h3>
<p>
  <table class="pretty" width="80%">
    <tr>
    <th>Author no</th>
    <th>Name</th>
    <th>Email</th>
    <th>Country team</th>
    <th>Focus/Writing group</th>
    </tr>
    <% if !@publication.authors %>
      <% if @publication.authors.first.number == 0 %>
        <% addend = 1 %>
      <% else %>
        <% addend = 0 %>
      <% end %>
    <% end %>
     <% @publication.authors.each do |a| %>
     <tr>
      <% if a.number.is_a? Integer and @object.try(:a) %>
        <td><%=h (a.number+addend).ordinalize %></td>
      <% else %>
        <td><%=h (a.number+1).ordinalize %></td>
      <% end %>
      <td><%=h a.name %></td>
      <td><%=h a.email %></td>
      <td>
      <% unless a.country_team_id.nil? %>
        <%=h a.country_team.name %>
      <% end %>
    </td>
      <td>
      <% unless a.focus_group_id.nil? %>
        <%=h a.focus_group.name %>
      <% end %>   
  </td>     
     </tr>
     <% end %>   
  </table>
</p>

<p>
  <% if @publication.user %>
  <table class="pretty" width="80%">
    <tr>
      <th>Contact</th>
      <th>Name</th>
      <th>Email</th>
    </tr>
    <tr>
      <td>HBSC responsible author</td>
      <td><%=h @publication.user.name %></td>
      <td><%=h @publication.user.email %></td>    
    </tr>
    </table>
    <% else %>
    <div class="alert alert-error">NO RESPONSIBLE AUTHOR - PLEASE FIX THIS ISSUE!</div>
    <% end %>
</p>

<h3>Data</h3>
<div class="line_of_boxes">
  <div class="box_in_line">
    Survey data:
    <div class="box_in_line_content">
      <% @foundations.each do |foundation| %>
        <div class="child">
            <%=h foundation.survey_name %><br />
        </div>
      <% end %>
      </div>
  </div>
  <div class="box_in_line">
    Population(s):
    <div class="box_in_line_content">
      <% @inclusions.each do |inclusion| %>
        <div class="child">
            <%=h inclusion.population_name %><br />
        </div>
      <% end %>
      </div>
  </div>
   <div class="box_bottom"></div>
</div>

<h3>Variables</h3>
 <div class="line_of_boxes">
  <% if @publication.outcome_variables %>
  <div class="box_in_line">
    Outcome measure(s):
    <div class="box_in_line_content">
      <% @publication.outcome_variables.each do |outcome| %>
        <div class="child">
            <%=h outcome.name %><br />
        </div>
      <% end %>
      </div>
  </div>
  <% end %>
  <% if @publication.determinant_variables %>
  <div class="box_in_line">
    Determinant(s):
    <div class="box_in_line_content">
      <% @publication.determinant_variables.each do |determinant| %>
      <div class="child">
          <%=h determinant.name %></br />
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
  <% if @publication.mediator_variables %>
  <div class="box_in_line">
    Other key variables:
    <div class="box_in_line_content">
    <% @publication.mediator_variables.each do |mediator| %>
      <div class="child">
        <%=h mediator.name %><br />
      </div>
    <% end %>
    </div>
  </div>
  <% end %>

   <div class="box_bottom"></div>
</div>


<p>
  <strong>Target Journal:</strong>
<% if @publication.target_journal %>
      <%=h @publication.target_journal.name %>
<% end %>
</p>
<p>
  <strong>Publication URL:</strong>
  <%=link_to @publication.url, @publication.url %>
</p>
<p>
  <strong>Reference/Citation:</strong>
  <%=h @publication.reference %>
</p>
<p>
  <strong>Current State:</strong>
  <%=h @publication.state.humanize %>
</p>
<% if !@publication.notes.empty? && ( current_user.roles.include?("publication_group") || @publication.user_id == current_user.id ) %>
<table class="pretty">
  <tr>
    <th align="left">State</th>
    <th>Date</th>
    <th>User</th>
    <th>Notes</th>
  </tr>
  <% for notes in @publication.notes %>
    <tr>
      <td><%=h notes.state.humanize %></td>
      <td><%=h notes.created_at.strftime('%Y-%m-%d %H:%M') %></td>
      <td><%=h notes.user.full_name %></td>
      <td><%=h notes.content %></td>
    </tr>
  <% end %>
</table>
<% end %>

<div class="form-actions">
<% if @publication.state == "preplanned" %>
  <%= link_to "Submit", preplanned_submit_publication_path(@publication), :method => :put, class: 'btn btn-primary' if permitted_to? :submit, :publications %>
  <%= link_to "Submit for removal", preplanned_removal_request_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :submit, :publications %>  
<% elsif @publication.state == "preplanned_submitted" %>
  <%= link_to "Accept as planned", preplanned_accept_publication_path(@publication), :method => :put, class: 'btn btn-success' if permitted_to? :progress, :publications %>
  <%= link_to "Reject as planned", preplanned_reject_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :progress, :publications %>

<% elsif @publication.state == "preplanned_removal_requested" %>
  <%= link_to "Accept removal", removal_accept_publication_path(@publication), :method => :put, class: 'btn btn-warning' if permitted_to? :progress, :publications %>
  <%= link_to "Reject removal", preplanned_removal_reject_publication_path(@publication), :method => :put, class: 'btn btn-info' if permitted_to? :progress, :publications %>



<% elsif @publication.state == "planned" %>
  <%= link_to "Submit", planned_submit_publication_path(@publication), :method => :put, class: 'btn btn-primary' if permitted_to? :submit, :publications %>
  <%= link_to "Submit for removal", planned_removal_request_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :submit, :publications %>    
<% elsif @publication.state == "planned_submitted" %>
  <%= link_to "Accept as in progress", planned_accept_publication_path(@publication), :method => :put, class: 'btn btn-success' if permitted_to? :progress, :publications %> 
  <%= link_to "Reject as in progress", planned_reject_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :progress, :publications %>

<% elsif @publication.state == "planned_removal_requested" %>
  <%= link_to "Accept removal", removal_accept_publication_path(@publication), :method => :put, class: 'btn btn-warning' if permitted_to? :progress, :publications %>
  <%= link_to "Reject removal", planned_removal_reject_publication_path(@publication), :method => :put, class: 'btn btn-info' if permitted_to? :progress, :publications %>


<% elsif @publication.state == "inprogress" %>
  <%= link_to "Submit", inprogress_submit_publication_path(@publication), :method => :put, class: 'btn btn-primary' if permitted_to? :submit, :publications %>
  <%= link_to "Submit for removal", inprogress_removal_request_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :submit, :publications %>  
<% elsif @publication.state == "inprogress_submitted" %>
  <%= link_to "Accept as submitted", inprogress_accept_publication_path(@publication), :method => :put, class: 'btn btn-success' if permitted_to? :progress, :publications %>
  <%= link_to "Reject as submitted", inprogress_reject_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :progress, :publications %>

<% elsif @publication.state == "inprogress_removal_requested" %>
  <%= link_to "Accept removal", removal_accept_publication_path(@publication), :method => :put, class: 'btn btn-warning' if permitted_to? :progress, :publications %>
  <%= link_to "Reject removal", inprogress_removal_reject_publication_path(@publication), :method => :put, class: 'btn btn-info' if permitted_to? :progress, :publications %>

<% elsif @publication.state == "submitted" %>
  <%= link_to "Submit", submitted_submit_publication_path(@publication), :method => :put, class: 'btn btn-primary' if permitted_to? :submit, :publications %>
  <%= link_to "Submit for removal", submitted_removal_request_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :submit, :publications %>  
<% elsif @publication.state == "submitted_submitted" %>
  <%= link_to "Accept as accepted", submitted_accept_publication_path(@publication), :method => :put, class: 'btn btn-success' if permitted_to? :progress, :publications %>
  <%= link_to "Reject as accepted", submitted_reject_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :progress, :publications %>

<% elsif @publication.state == "submitted_removal_requested" %>
  <%= link_to "Accept removal", removal_accept_publication_path(@publication), :method => :put, class: 'btn btn-warning' if permitted_to? :progress, :publications %>
  <%= link_to "Reject removal", submitted_removal_reject_publication_path(@publication), :method => :put, class: 'btn btn-info' if permitted_to? :progress, :publications %>

<% elsif @publication.state == "accepted" %>
  <%= link_to "Submit", accepted_submit_publication_path(@publication), :method => :put, class: 'btn btn-primary' if permitted_to? :submit, :publications %>
  <%= link_to "Submit for removal", accepted_removal_request_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :submit, :publications %>    
<% elsif @publication.state == "accepted_submitted" %>
  <%= link_to "Accept as published", accepted_accept_publication_path(@publication), :method => :put, class: 'btn btn-success' if permitted_to? :progress, :publications %>
  <%= link_to "Reject as published", accepted_reject_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :progress, :publications %>

<% elsif @publication.state == "accepted_removal_requested" %>
  <%= link_to "Accept removal", removal_accept_publication_path(@publication), :method => :put, class: 'btn btn-warning' if permitted_to? :progress, :publications %>
  <%= link_to "Reject removal", accepted_removal_reject_publication_path(@publication), :method => :put, class: 'btn btn-info' if permitted_to? :progress, :publications %>

<% elsif @publication.state == "published" %>
  <%= link_to "Submit for removal", published_removal_request_publication_path(@publication), :method => :put, class: 'btn btn-danger' if permitted_to? :submit, :publications %>  

<% elsif @publication.state == "published_removal_requested" %>
  <%= link_to "Accept removal", removal_accept_publication_path(@publication), :method => :put, class: 'btn btn-warning' if permitted_to? :progress, :publications %>
  <%= link_to "Reject removal", published_removal_reject_publication_path(@publication), :method => :put, class: 'btn btn-info' if permitted_to? :progress, :publications %>

<% end %>
<%= link_to "PDF version", publication_path(@publication, :format => "pdf"), class: 'btn btn-inverse' %>
</div>

<p id="pdf_link">
  <%= link_to "Edit", edit_publication_path(@publication) if permitted_to? :edit, :publications %> |
  <%= link_to "Destroy", @publication, :confirm => 'Are you sure?', :method => :delete if permitted_to? :destroy, :publications %> |
  <%= link_to "View All", publications_path %>
</p>