config/routes.rb
PumaApp::Application.routes.draw do
  resources :authors do
    collection do
      post 'sort'
    end
  end

  resources :emails
  resources :notes
  resources :target_journals
  resources :variables
  resources :focus_groups
  resources :country_teams
  resources :populations
  resources :publication_types
  resources :surveys
  resources :languages
  resources :pages

  resources :publications do
    collection do
      get 'list'
      post 'import'
    end
    member do 
      put 'preplanned_submit'
      put 'preplanned_accept'
      put 'preplanned_reject' 
      put 'preplanned_remind'
      put 'planned_submit'
      put 'planned_accept'
      put 'planned_reject' 
      put 'planned_remind'
      put 'inprogress_submit'  
      put 'inprogress_accept'
      put 'inprogress_reject' 
      put 'inprogress_remind'
      put 'submitted_submit'  
      put 'submitted_accept'
      put 'submitted_reject'
      put 'submitted_remind'
      put 'accepted_submit'  
      put 'accepted_accept'
      put 'accepted_reject'
      put 'accepted_remind'
      put 'preplanned_removal_request'
      put 'planned_removal_request'
      put 'inprogress_removal_request'
      put 'submitted_removal_request'
      put 'accepted_removal_request'
      put 'published_removal_request'
      put 'removal_accept'
      put 'preplanned_removal_reject'
      put 'planned_removal_reject'
      put 'inprogress_removal_reject'
      put 'submitted_removal_reject'
      put 'accepted_removal_reject'
      put 'published_removal_reject'
      put 'unlock'
      put 'archive'
      put 'unarchive'
      get 'audit'
    end
  end

  devise_for :users
  scope "/admin" do 
    resources :users
  end

  root to: 'pages#home'
  match '/about',     to: 'pages#about'
  match '/contact',   to: 'pages#contact'
  match '/master',    to: 'pages#master' 
  match '/no_access', to: 'pages#no_access' 

end

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Survey < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  filter_resource_access
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys.where("name ILIKE ?", "%#{params[:q]}%") }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    #@survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    #@survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    #@survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    #@survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    #@survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    #@survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
end

app/views/surveys/_form.html.erb
<%= simple_form_for(@survey) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>Listing Surveys</h1>

<table id="master_data" class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th class="text-right">Used in # articles</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.name %></td>
    <td class="text-right"><%= Foundation.count(conditions: { survey_id: survey.id } ) %></td>
    <td class="text-right"><%= link_to 'Edit', edit_survey_path(survey) %></td>
    <td class="text-right"><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br /><br />
<br />
<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @survey.name %>
</p>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>