config/routes.rb
PumaApp::Application.routes.draw do
  resources :authors do
    collection do
      post 'sort'
    end
  end

  resources :emails
  resources :notes
  resources :target_journals
  resources :variables
  resources :focus_groups
  resources :country_teams
  resources :populations
  resources :publication_types
  resources :surveys
  resources :languages
  resources :pages

  resources :publications do
    collection do
      get 'list'
      post 'import'
    end
    member do 
      put 'preplanned_submit'
      put 'preplanned_accept'
      put 'preplanned_reject' 
      put 'preplanned_remind'
      put 'planned_submit'
      put 'planned_accept'
      put 'planned_reject' 
      put 'planned_remind'
      put 'inprogress_submit'  
      put 'inprogress_accept'
      put 'inprogress_reject' 
      put 'inprogress_remind'
      put 'submitted_submit'  
      put 'submitted_accept'
      put 'submitted_reject'
      put 'submitted_remind'
      put 'accepted_submit'  
      put 'accepted_accept'
      put 'accepted_reject'
      put 'accepted_remind'
      put 'preplanned_removal_request'
      put 'planned_removal_request'
      put 'inprogress_removal_request'
      put 'submitted_removal_request'
      put 'accepted_removal_request'
      put 'published_removal_request'
      put 'removal_accept'
      put 'preplanned_removal_reject'
      put 'planned_removal_reject'
      put 'inprogress_removal_reject'
      put 'submitted_removal_reject'
      put 'accepted_removal_reject'
      put 'published_removal_reject'
      put 'unlock'
      put 'archive'
      put 'unarchive'
      get 'audit'
    end
  end

  devise_for :users
  scope "/admin" do 
    resources :users
  end

  root to: 'pages#home'
  match '/about',     to: 'pages#about'
  match '/contact',   to: 'pages#contact'
  match '/master',    to: 'pages#master' 
  match '/no_access', to: 'pages#no_access' 

end

app/controllers/publication_types_controller.rb
class PublicationTypesController < ApplicationController
  filter_resource_access
  # GET /publication_types
  # GET /publication_types.json
  def index
    @publication_types = PublicationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publication_types }
    end
  end

  # GET /publication_types/1
  # GET /publication_types/1.json
  def show
    #@publication_type = PublicationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publication_type }
    end
  end

  # GET /publication_types/new
  # GET /publication_types/new.json
  def new
    #@publication_type = PublicationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publication_type }
    end
  end

  # GET /publication_types/1/edit
  def edit
    #@publication_type = PublicationType.find(params[:id])
  end

  # POST /publication_types
  # POST /publication_types.json
  def create
    #@publication_type = PublicationType.new(params[:publication_type])

    respond_to do |format|
      if @publication_type.save
        format.html { redirect_to @publication_type, notice: 'Publication type was successfully created.' }
        format.json { render json: @publication_type, status: :created, location: @publication_type }
      else
        format.html { render action: "new" }
        format.json { render json: @publication_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publication_types/1
  # PUT /publication_types/1.json
  def update
    #@publication_type = PublicationType.find(params[:id])

    respond_to do |format|
      if @publication_type.update_attributes(params[:publication_type])
        format.html { redirect_to @publication_type, notice: 'Publication type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publication_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publication_types/1
  # DELETE /publication_types/1.json
  def destroy
    #@publication_type = PublicationType.find(params[:id])
    @publication_type.destroy

    respond_to do |format|
      format.html { redirect_to publication_types_url }
      format.json { head :no_content }
    end
  end
end

app/views/publication_types/_form.html.erb
<%= simple_form_for(@publication_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/publication_types/edit.html.erb
<h1>Editing Publication Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication_type %> |
<%= link_to 'Back', publication_types_path %>

app/views/publication_types/index.html.erb
<h1>Listing Publication Types</h1>

<table id="master_data" class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th class="text-right">Used in # articles</th>
    <th></th>
    <th></th>
  </tr>
</thead><tbody>
<% @publication_types.each do |publication_type| %>
  <tr>
    <td><%= publication_type.name %></td>
    <td class="text-right"><%= Publication.count(conditions: { publication_type_id: publication_type.id } ) %></td>
    <td class="text-right"><%= link_to 'Edit', edit_publication_type_path(publication_type) %></td>
    <td class="text-right"><%= link_to 'Destroy', publication_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Publication type', new_publication_type_path %>

app/views/publication_types/new.html.erb
<h1>New Publication Type</h1>

<%= render 'form' %>

<%= link_to 'Back', publication_types_path %>

app/views/publication_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @publication_type.name %>
</p>


<%= link_to 'Edit', edit_publication_type_path(@publication_type) %> |
<%= link_to 'Back', publication_types_path %>