config/routes.rb
PumaApp::Application.routes.draw do
  resources :authors do
    collection do
      post 'sort'
    end
  end

  resources :emails
  resources :notes
  resources :target_journals
  resources :variables
  resources :focus_groups
  resources :country_teams
  resources :populations
  resources :publication_types
  resources :surveys
  resources :languages
  resources :pages

  resources :publications do
    collection do
      get 'list'
      post 'import'
    end
    member do 
      put 'preplanned_submit'
      put 'preplanned_accept'
      put 'preplanned_reject' 
      put 'preplanned_remind'
      put 'planned_submit'
      put 'planned_accept'
      put 'planned_reject' 
      put 'planned_remind'
      put 'inprogress_submit'  
      put 'inprogress_accept'
      put 'inprogress_reject' 
      put 'inprogress_remind'
      put 'submitted_submit'  
      put 'submitted_accept'
      put 'submitted_reject'
      put 'submitted_remind'
      put 'accepted_submit'  
      put 'accepted_accept'
      put 'accepted_reject'
      put 'accepted_remind'
      put 'preplanned_removal_request'
      put 'planned_removal_request'
      put 'inprogress_removal_request'
      put 'submitted_removal_request'
      put 'accepted_removal_request'
      put 'published_removal_request'
      put 'removal_accept'
      put 'preplanned_removal_reject'
      put 'planned_removal_reject'
      put 'inprogress_removal_reject'
      put 'submitted_removal_reject'
      put 'accepted_removal_reject'
      put 'published_removal_reject'
      put 'unlock'
      put 'archive'
      put 'unarchive'
      get 'audit'
    end
  end

  devise_for :users
  scope "/admin" do 
    resources :users
  end

  root to: 'pages#home'
  match '/about',     to: 'pages#about'
  match '/contact',   to: 'pages#contact'
  match '/master',    to: 'pages#master' 
  match '/no_access', to: 'pages#no_access' 

end

app/models/population.rb
# == Schema Information
#
# Table name: populations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Population < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name  
end

app/controllers/populations_controller.rb
class PopulationsController < ApplicationController
  filter_resource_access
  # GET /populations
  # GET /populations.json
  def index
    @populations = Population.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @populations.where("name ILIKE ?", "%#{params[:q]}%") }
    end
  end

  # GET /populations/1
  # GET /populations/1.json
  def show
    #@population = Population.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @population }
    end
  end

  # GET /populations/new
  # GET /populations/new.json
  def new
    #@population = Population.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @population }
    end
  end

  # GET /populations/1/edit
  def edit
    #@population = Population.find(params[:id])
  end

  # POST /populations
  # POST /populations.json
  def create
    #@population = Population.new(params[:population])

    respond_to do |format|
      if @population.save
        format.html { redirect_to @population, notice: 'Population was successfully created.' }
        format.json { render json: @population, status: :created, location: @population }
      else
        format.html { render action: "new" }
        format.json { render json: @population.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /populations/1
  # PUT /populations/1.json
  def update
    #@population = Population.find(params[:id])

    respond_to do |format|
      if @population.update_attributes(params[:population])
        format.html { redirect_to @population, notice: 'Population was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @population.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /populations/1
  # DELETE /populations/1.json
  def destroy
    #@population = Population.find(params[:id])
    @population.destroy

    respond_to do |format|
      format.html { redirect_to populations_url }
      format.json { head :no_content }
    end
  end
end

app/views/populations/_form.html.erb
<%= simple_form_for(@population) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/populations/edit.html.erb
<h1>Editing population</h1>

<%= render 'form' %>

<%= link_to 'Show', @population %> |
<%= link_to 'Back', populations_path %>

app/views/populations/index.html.erb
<h1>Listing Populations</h1>

<table id="master_data" class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th class="text-right">Used in # articles</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @populations.each do |population| %>
  <tr>
    <td><%= population.name %></td>
    <td class="text-right"><%= Inclusion.count(conditions: { population_id: population.id } ) %></td>
    <td class="text-right"><%= link_to 'Edit', edit_population_path(population) %></td>
    <td class="text-right"><%= link_to 'Destroy', population, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br /><br /><br />

<%= link_to 'New Population', new_population_path %>

app/views/populations/new.html.erb
<h1>New population</h1>

<%= render 'form' %>

<%= link_to 'Back', populations_path %>

app/views/populations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @population.name %>
</p>


<%= link_to 'Edit', edit_population_path(@population) %> |
<%= link_to 'Back', populations_path %>